### PR TITLE
Also use serde traits when only serde_with-3 is enabled

### PR DESCRIPTION
**Pull request by maximdeclercq**

### CODE REVIEW

**Comment by isabelatkinson** [comment]
Hi @maximdeclercq, thanks for making this PR! I see that this fixes compilation errors when using the `serde_with-3` feature with `chrono-0_4` or `time-0_3`. I've just authorized a CI run and will merge this assuming that passes.

**Comment by isabelatkinson** [comment]
Hi @maximdeclercq, CI looks good (there is one unrelated lint failure that was fixed by #424) so I am going to merge this. Thank you for your contribution!
